default:
  notify:
    title: '听客来-pc端' # 推送时候的标题，可自定义

ia32-beta:
  build:
    - 'npm run build-ia32-beta'
  convert:
    target: package-ia32-beta/beta.yml
    dest: package-ia32-beta/beta.json
  resource:
    - dist: 'package-ia32-beta' # 资源所在目录 或者 文件路径
      ignore:
        - 'win-ia32-unpacked'
        - '/.yml$/'
        - '/.blockmap$/'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/win/ia32/beta'
  fileReplace:
    - dist: 'package-ia32-beta/beta.yml' # 资源所在目录 或者 文件路径
      target: 'beta.yml'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/win/ia32/beta'
    - dist: 'package-ia32-beta/beta.json' # 资源所在目录 或者 文件路径
      target: 'beta.json'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/win/ia32/beta'

ia32-check:
  build:
    - 'npm run build-ia32-release'
  convert:
    target: package-ia32-release/release.yml
    dest: package-ia32-release/release.json
  resource:
    - dist: 'package-ia32-release' # 资源所在目录 或者 文件路径
      ignore:
        - 'win-ia32-unpacked'
        - '/.yml$/'
        - '/.blockmap$/'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/win/ia32/check'
  fileReplace:
    - dist: 'package-ia32-release/release.yml' # 资源所在目录 或者 文件路径
      target: 'release.yml'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/win/ia32/check'
    - dist: 'package-ia32-release/release.json' # 资源所在目录 或者 文件路径
      target: 'release.json'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/win/ia32/check'

ia32-release:
  build:
    - 'npm run build-ia32-release'
  convert:
    target: package-ia32-release/release.yml
    dest: package-ia32-release/release.json
  resource:
    - dist: 'package-ia32-release' # 资源所在目录 或者 文件路径
      ignore:
        - 'win-ia32-unpacked'
        - '/.yml$/'
        - '/.blockmap$/'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/win/ia32/release'
  fileReplace:
    - dist: 'package-ia32-release/release.yml' # 资源所在目录 或者 文件路径
      target: 'release.yml'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/win/ia32/release'
    - dist: 'package-ia32-release/release.json' # 资源所在目录 或者 文件路径
      target: 'release.json'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/win/ia32/release'

x64-beta:
  build:
    - 'npm run build-x64-beta'
  convert:
    target: package-x64-beta/beta.yml
    dest: package-x64-beta/beta.json
  resource:
    - dist: 'package-x64-beta' # 资源所在目录 或者 文件路径
      ignore:
        - 'win-unpacked'
        - '/.yml$/'
        - '/.blockmap$/'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/win/x64/beta'
  fileReplace:
    - dist: 'package-x64-beta/beta.yml' # 资源所在目录 或者 文件路径
      target: 'beta.yml'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/win/x64/beta'
    - dist: 'package-x64-beta/beta.json' # 资源所在目录 或者 文件路径
      target: 'beta.json'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/win/x64/beta'

x64-check:
  build:
    - 'npm run build-x64-release'
  convert:
    target: package-x64-release/release.yml
    dest: package-x64-release/release.json
  resource:
    - dist: 'package-x64-release' # 资源所在目录 或者 文件路径
      ignore:
        - 'win-unpacked'
        - '/.yml$/'
        - '/.blockmap$/'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/win/x64/check'
  fileReplace:
    - dist: 'package-x64-release/release.yml' # 资源所在目录 或者 文件路径
      target: 'release.yml'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/win/x64/check'
    - dist: 'package-x64-release/release.json' # 资源所在目录 或者 文件路径
      target: 'release.json'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/win/x64/check'

x64-release:
  build:
    - 'npm run build-x64-release'
  convert:
    target: package-x64-release/release.yml
    dest: package-x64-release/release.json
  resource:
    - dist: 'package-x64-release' # 资源所在目录 或者 文件路径
      ignore:
        - 'win-unpacked'
        - '/.yml$/'
        - '/.blockmap$/'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/win/x64/release'
  fileReplace:
    - dist: 'package-x64-release/release.yml' # 资源所在目录 或者 文件路径
      target: 'release.yml'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/win/x64/release'
    - dist: 'package-x64-release/release.json' # 资源所在目录 或者 文件路径
      target: 'release.json'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/win/x64/release'

mac-beta:
  build:
    - 'npm run build-mac-beta'
  convert:
    target: package-beta/beta-mac.yml
    dest: package-beta/beta-mac.json
  resource:
    - dist: 'package-beta' # 资源所在目录 或者 文件路径
      ignore:
        - 'mac'
        - '/.yml$/'
        - '/.json/'
        - '/.blockmap$/'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/mac/beta'
  fileReplace:
    - dist: 'package-beta/beta-mac.yml' # 资源所在目录 或者 文件路径
      target: 'beta-mac.yml'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/mac/beta'
    - dist: 'package-beta/beta-mac.json' # 资源所在目录 或者 文件路径
      target: 'beta-mac.json'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/mac/beta'

mac-check:
  build:
    - 'npm run build-mac-release'
  convert:
    target: package-release/release-mac.yml
    dest: package-release/release-mac.json
  resource:
    - dist: 'package-release' # 资源所在目录 或者 文件路径
      ignore:
        - 'mac'
        - '/.yml$/'
        - '/.json/'
        - '/.blockmap$/'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/mac/check'
  fileReplace:
    - dist: 'package-release/release-mac.yml' # 资源所在目录 或者 文件路径
      target: 'release-mac.yml'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/mac/check'
    - dist: 'package-release/release-mac.json'
      target: 'release-mac.json'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/mac/check'

mac-release:
  build:
    - 'npm run build-mac-release'
  convert:
    target: package-release/release-mac.yml
    dest: package-release/release-mac.json
  resource:
    - dist: 'package-release' # 资源所在目录 或者 文件路径
      ignore:
        - 'mac'
        - '/.yml$/'
        - '/.json/'
        - '/.blockmap$/'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/mac/release'
  fileReplace:
    - dist: 'package-release/release-mac.yml' # 资源所在目录 或者 文件路径
      target: 'release-mac.yml'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/mac/release'
    - dist: 'package-release/release-mac.json'
      target: 'release-mac.json'
      upload: # 以下指定上传资源文件要用的方式，如果指定多个，会依次使用上传
        - type: 'aliyunOss'
          param:
            accessKeyId: ${ALY_OSS_Access_Id}
            secretAccessKey: ${ALY_OSS_Access_Key}
            bucket: 'tingkelai-client'
            endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
            prefix: 'pc-autoupdate/mac/release'
